### ISSUE TITLE
enhancement - debug view of sphere / transparent live video view (optional)

### ISSUE THREAD

**Issue by johndpope** [scihant/CTPanoramaView#1]
Did you consider a kind of debug view to show spheres / perhaps with flexible radius? 

<img width="674" alt="screen shot 2017-03-06 at 12 37 13 pm" src="https://cloud.githubusercontent.com/assets/289994/23621654/a64a23ba-0269-11e7-9f47-3e668239199c.png">

http://paulbourke.net/dome/fish2/

**Comment by scihant** [comment]
I don't do the projections manually. They do happen automatically because of the arrangement of the 3D geometry and the camera in the scene. Therefore showing debug views such as those wouldn't be much useful. One could use special images to test the accuracy of the projections, but I don't think that it's something users really need. It'd be more like a gimmick at this point.

**Comment by johndpope** [comment]
Thing is / I want to use/extend this library for augmented reality. Given its using SceneKit / did you know you can import 3D models out of the box? Also / consider that given this library is open source other developers may want to take this work on and chime in to help.(it's a pity all suggestions are bundled in as issues.) mapping the pixels to physical space would be critical for that kind of work to succeed (not a gimmick)

**Comment by scihant** [comment]
I'm aware that this was as suggestion and not an issue. I've started the project simply to display panoramic images and that's why haven't thought about its potential use cases in AR. Especially since it currently lacks features such as partial panorama support which are more relevant to its actual use cases I had in mind. Of course this doesn't mean that if someone does the work and sends a pull request, I'll ignore it :) It just isn't among my priorities right now.  

Btw, SceneKit already has methods that project/unproject points that can be used to map the coordinates between the scene coordinates and pixel coordinates. So the mapping you're referring to should not be so hard to do even now, if that's what you're looking for.
