### ISSUE TITLE
Public property for start angle?

### ISSUE THREAD

**Issue by MirstrKot** [scihant/CTPanoramaView#17]
Is it possible change start angle from 0,0,0 to the center of my spherical picture? I found random picture in google to illustrate it: For example http://paulbourke.net/fun/dragongardens/2.jpg
the gates is the most important part of panorama and I want to start viewing from the center of image.

**Comment by MirstrKot** [comment]
I made pull request. Please review it, is it good enough or need some improvements.

**Comment by scihant** [comment]
Thanks for the pull request but I haven't seen it until now sorry for the late response.
I had already added the property on the dev branch but haven't pushed it yet.

The main difference from your implementation is that it takes the value as radians since that's the standard unit when dealing with APIs like this.  

I'll review your PR anyway.
