### ISSUE TITLE
Add Support to SPM

### ISSUE THREAD

**Issue by shshalom** [scihant/CTPanoramaView#64]
please add support to the swift package manager.

**Comment by Appracatappra** [comment]
Hi shshalom, I've taken scihant's excellent work on this library, made a SwiftUI version and released it as a Swift Package Manager Package [https://github.com/Appracatappra/SwiftUIPanoramaViewer](https://github.com/Appracatappra/SwiftUIPanoramaViewer). Since I made so many changes that take it away from its initial design, I've released it as a new library instead of making a pull request on this one.

**Comment by scihant** [comment]
Added by #67
